<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * ISO country list (263 rows) transcribed from the main project database
 * (project_icmria.countries). IDs are preserved because profiles.country_id and
 * paper_authors.country_id reference them.
 *
 * Idempotent: uses upsert keyed on `id`, so it is safe to re-run.
 * `is_active = 0` rows (Israel, "Other") are kept exactly as in the source DB.
 */
class CountriesTableSeeder extends Seeder
{
    public function run(): void
    {
        // [id, name, code, slug, sort_order, is_active]
        $data = [
            [1, 'Afghanistan', 'AFG', 'afghanistan', 1, 1],
            [2, 'Albania', 'ALB', 'albania', 2, 1],
            [3, 'Algeria', 'DZA', 'algeria', 3, 1],
            [4, 'American Samoa', 'ASM', 'american-samoa', 4, 1],
            [5, 'Andorra', 'AND', 'andorra', 5, 1],
            [6, 'Angola', 'AGO', 'angola', 6, 1],
            [7, 'Anguilla', 'AIA', 'anguilla', 7, 1],
            [8, 'Antarctica', 'ATA', 'antarctica', 8, 1],
            [9, 'Antigua and Barbuda', 'ATG', 'antigua-and-barbuda', 9, 1],
            [10, 'Argentina', 'ARG', 'argentina', 10, 1],
            [11, 'Armenia', 'ARM', 'armenia', 11, 1],
            [12, 'Aruba', 'ABW', 'aruba', 12, 1],
            [13, 'Australia', 'AUS', 'australia', 13, 1],
            [14, 'Austria', 'AUT', 'austria', 14, 1],
            [15, 'Azerbaijan', 'AZE', 'azerbaijan', 15, 1],
            [16, 'Bahamas', 'BHS', 'bahamas', 16, 1],
            [17, 'Bahrain', 'BHR', 'bahrain', 17, 1],
            [18, 'Bangladesh', 'BGD', 'bangladesh', 18, 1],
            [19, 'Barbados', 'BRB', 'barbados', 19, 1],
            [20, 'Belarus', 'BLR', 'belarus', 20, 1],
            [21, 'Belgium', 'BEL', 'belgium', 21, 1],
            [22, 'Belize', 'BLZ', 'belize', 22, 1],
            [23, 'Benin', 'BEN', 'benin', 23, 1],
            [24, 'Bermuda', 'BMU', 'bermuda', 24, 1],
            [25, 'Bhutan', 'BTN', 'bhutan', 25, 1],
            [26, 'Bolivia', 'BOL', 'bolivia', 26, 1],
            [27, 'Bosnia and Herzegovina', 'BIH', 'bosnia-and-herzegovina', 27, 1],
            [28, 'Botswana', 'BWA', 'botswana', 28, 1],
            [29, 'Bouvet Island', 'BVT', 'bouvet-island', 29, 1],
            [30, 'Brazil', 'BRA', 'brazil', 30, 1],
            [31, 'British Antarctic Territory', 'BES', 'british-antarctic-territory', 31, 1],
            [32, 'British Indian Ocean Territory', 'IOT', 'british-indian-ocean-territory', 32, 1],
            [33, 'British Virgin Islands', 'VGB', 'british-virgin-islands', 33, 1],
            [34, 'Brunei', 'BRN', 'brunei', 34, 1],
            [35, 'Bulgaria', 'BGR', 'bulgaria', 35, 1],
            [36, 'Burkina Faso', 'BFA', 'burkina-faso', 36, 1],
            [37, 'Burundi', 'BDI', 'burundi', 37, 1],
            [38, 'Cambodia', 'KHM', 'cambodia', 38, 1],
            [39, 'Cameroon', 'CMR', 'cameroon', 39, 1],
            [40, 'Canada', 'CAN', 'canada', 40, 1],
            [41, 'Canton and Enderbury Islands', 'CTE', 'canton-and-enderbury-islands', 41, 1],
            [42, 'Cape Verde', 'CPV', 'cape-verde', 42, 1],
            [43, 'Cayman Islands', 'CYM', 'cayman-islands', 43, 1],
            [44, 'Central African Republic', 'CAF', 'central-african-republic', 44, 1],
            [45, 'Chad', 'TCD', 'chad', 45, 1],
            [46, 'Chile', 'CHL', 'chile', 46, 1],
            [47, 'China', 'CHN', 'china', 47, 1],
            [48, 'Christmas Island', 'CXR', 'christmas-island', 48, 1],
            [49, 'Cocos [Keeling] Islands', 'CCK', 'cocos-keeling-islands', 49, 1],
            [50, 'Colombia', 'COL', 'colombia', 50, 1],
            [51, 'Comoros', 'COM', 'comoros', 51, 1],
            [52, 'Congo - Brazzaville', 'COG', 'congo-brazzaville', 52, 1],
            [53, 'Congo - Kinshasa', 'COD', 'congo-kinshasa', 53, 1],
            [54, 'Cook Islands', 'COK', 'cook-islands', 54, 1],
            [55, 'Costa Rica', 'CRI', 'costa-rica', 55, 1],
            [56, 'Croatia', 'HRV', 'croatia', 56, 1],
            [57, 'Cuba', 'CUB', 'cuba', 57, 1],
            [58, 'Curaçao', 'CUW', 'curacao', 58, 1],
            [59, 'Cyprus', 'CYP', 'cyprus', 59, 1],
            [60, 'Czech Republic', 'CZE', 'czech-republic', 60, 1],
            [61, 'Côte d\'Ivoire', 'CIV', 'cote-divoire', 61, 1],
            [62, 'Denmark', 'DNK', 'denmark', 62, 1],
            [63, 'Djibouti', 'DJI', 'djibouti', 63, 1],
            [64, 'Dominica', 'DMA', 'dominica', 64, 1],
            [65, 'Dominican Republic', 'DOM', 'dominican-republic', 65, 1],
            [66, 'Dronning Maud Land', 'ATN', 'dronning-maud-land', 66, 1],
            [67, 'Ecuador', 'ECU', 'ecuador', 67, 1],
            [68, 'Egypt', 'EGY', 'egypt', 68, 1],
            [69, 'El Salvador', 'SLV', 'el-salvador', 69, 1],
            [70, 'Equatorial Guinea', 'GNQ', 'equatorial-guinea', 70, 1],
            [71, 'Eritrea', 'ERI', 'eritrea', 71, 1],
            [72, 'Estonia', 'EST', 'estonia', 72, 1],
            [73, 'Ethiopia', 'ETH', 'ethiopia', 73, 1],
            [74, 'Falkland Islands', 'FLK', 'falkland-islands', 74, 1],
            [75, 'Faroe Islands', 'FRO', 'faroe-islands', 75, 1],
            [76, 'Fiji', 'FJI', 'fiji', 76, 1],
            [77, 'Finland', 'FIN', 'finland', 77, 1],
            [78, 'France', 'FRA', 'france', 78, 1],
            [79, 'French Guiana', 'GUF', 'french-guiana', 79, 1],
            [80, 'French Polynesia', 'PYF', 'french-polynesia', 80, 1],
            [81, 'French Southern Territories', 'ATF', 'french-southern-territories', 81, 1],
            [82, 'French Southern and Antarctic Territories', 'ATF2', 'french-southern-and-antarctic-territories', 82, 1],
            [83, 'Gabon', 'GAB', 'gabon', 83, 1],
            [84, 'Gambia', 'GMB', 'gambia', 84, 1],
            [85, 'Georgia', 'GEO', 'georgia', 85, 1],
            [86, 'Germany', 'DEU', 'germany', 86, 1],
            [87, 'Ghana', 'GHA', 'ghana', 87, 1],
            [88, 'Gibraltar', 'GIB', 'gibraltar', 88, 1],
            [89, 'Greece', 'GRC', 'greece', 89, 1],
            [90, 'Greenland', 'GRL', 'greenland', 90, 1],
            [91, 'Grenada', 'GRD', 'grenada', 91, 1],
            [92, 'Guadeloupe', 'GLP', 'guadeloupe', 92, 1],
            [93, 'Guam', 'GUM', 'guam', 93, 1],
            [94, 'Guatemala', 'GTM', 'guatemala', 94, 1],
            [95, 'Guernsey', 'GGY', 'guernsey', 95, 1],
            [96, 'Guinea', 'GIN', 'guinea', 96, 1],
            [97, 'Guinea-Bissau', 'GNB', 'guinea-bissau', 97, 1],
            [98, 'Guyana', 'GUY', 'guyana', 98, 1],
            [99, 'Haiti', 'HTI', 'haiti', 99, 1],
            [100, 'Heard Island and McDonald Islands', 'HMD', 'heard-island-and-mcdonald-islands', 100, 1],
            [101, 'Honduras', 'HND', 'honduras', 101, 1],
            [102, 'Hong Kong SAR China', 'HKG', 'hong-kong-sar-china', 102, 1],
            [103, 'Hungary', 'HUN', 'hungary', 103, 1],
            [104, 'Iceland', 'ISL', 'iceland', 104, 1],
            [105, 'India', 'IND', 'india', 105, 1],
            [106, 'Indonesia', 'IDN', 'indonesia', 106, 1],
            [107, 'Iran', 'IRN', 'iran', 107, 1],
            [108, 'Iraq', 'IRQ', 'iraq', 108, 1],
            [109, 'Ireland', 'IRL', 'ireland', 109, 1],
            [110, 'Isle of Man', 'IMN', 'isle-of-man', 110, 1],
            [111, 'Israel', 'ISR', 'israel', 111, 0],
            [112, 'Italy', 'ITA', 'italy', 112, 1],
            [113, 'Jamaica', 'JAM', 'jamaica', 113, 1],
            [114, 'Japan', 'JPN', 'japan', 114, 1],
            [115, 'Jersey', 'JEY', 'jersey', 115, 1],
            [116, 'Johnston Island', 'JTN', 'johnston-island', 116, 1],
            [117, 'Jordan', 'JOR', 'jordan', 117, 1],
            [118, 'Kazakhstan', 'KAZ', 'kazakhstan', 118, 1],
            [119, 'Kenya', 'KEN', 'kenya', 119, 1],
            [120, 'Kiribati', 'KIR', 'kiribati', 120, 1],
            [121, 'Kuwait', 'KWT', 'kuwait', 121, 1],
            [122, 'Kyrgyzstan', 'KGZ', 'kyrgyzstan', 122, 1],
            [123, 'Laos', 'LAO', 'laos', 123, 1],
            [124, 'Latvia', 'LVA', 'latvia', 124, 1],
            [125, 'Lebanon', 'LBN', 'lebanon', 125, 1],
            [126, 'Lesotho', 'LSO', 'lesotho', 126, 1],
            [127, 'Liberia', 'LBR', 'liberia', 127, 1],
            [128, 'Libya', 'LBY', 'libya', 128, 1],
            [129, 'Liechtenstein', 'LIE', 'liechtenstein', 129, 1],
            [130, 'Lithuania', 'LTU', 'lithuania', 130, 1],
            [131, 'Luxembourg', 'LUX', 'luxembourg', 131, 1],
            [132, 'Macau SAR China', 'MAC', 'macau-sar-china', 132, 1],
            [133, 'Macedonia', 'MKD', 'macedonia', 133, 1],
            [134, 'Madagascar', 'MDG', 'madagascar', 134, 1],
            [135, 'Malawi', 'MWI', 'malawi', 135, 1],
            [136, 'Malaysia', 'MYS', 'malaysia', 136, 1],
            [137, 'Maldives', 'MDV', 'maldives', 137, 1],
            [138, 'Mali', 'MLI', 'mali', 138, 1],
            [139, 'Malta', 'MLT', 'malta', 139, 1],
            [140, 'Marshall Islands', 'MHL', 'marshall-islands', 140, 1],
            [141, 'Martinique', 'MTQ', 'martinique', 141, 1],
            [142, 'Mauritania', 'MRT', 'mauritania', 142, 1],
            [143, 'Mauritius', 'MUS', 'mauritius', 143, 1],
            [144, 'Mayotte', 'MYT', 'mayotte', 144, 1],
            [145, 'Metropolitan France', 'FXX', 'metropolitan-france', 145, 1],
            [146, 'Mexico', 'MEX', 'mexico', 146, 1],
            [147, 'Micronesia', 'FSM', 'micronesia', 147, 1],
            [148, 'Midway Islands', 'MID', 'midway-islands', 148, 1],
            [149, 'Moldova', 'MDA', 'moldova', 149, 1],
            [150, 'Monaco', 'MCO', 'monaco', 150, 1],
            [151, 'Mongolia', 'MNG', 'mongolia', 151, 1],
            [152, 'Montenegro', 'MNE', 'montenegro', 152, 1],
            [153, 'Montserrat', 'MSR', 'montserrat', 153, 1],
            [154, 'Morocco', 'MAR', 'morocco', 154, 1],
            [155, 'Mozambique', 'MOZ', 'mozambique', 155, 1],
            [156, 'Myanmar [Burma]', 'MMR', 'myanmar-burma', 156, 1],
            [157, 'Namibia', 'NAM', 'namibia', 157, 1],
            [158, 'Nauru', 'NRU', 'nauru', 158, 1],
            [159, 'Nepal', 'NPL', 'nepal', 159, 1],
            [160, 'Netherlands', 'NLD', 'netherlands', 160, 1],
            [161, 'Netherlands Antilles', 'ANT', 'netherlands-antilles', 161, 1],
            [162, 'Neutral Zone', 'NTZ', 'neutral-zone', 162, 1],
            [163, 'New Caledonia', 'NCL', 'new-caledonia', 163, 1],
            [164, 'New Zealand', 'NZL', 'new-zealand', 164, 1],
            [165, 'Nicaragua', 'NIC', 'nicaragua', 165, 1],
            [166, 'Niger', 'NER', 'niger', 166, 1],
            [167, 'Nigeria', 'NGA', 'nigeria', 167, 1],
            [168, 'Niue', 'NIU', 'niue', 168, 1],
            [169, 'Norfolk Island', 'NFK', 'norfolk-island', 169, 1],
            [170, 'North Korea', 'PRK', 'north-korea', 170, 1],
            [171, 'North Vietnam', 'VDR', 'north-vietnam', 171, 1],
            [172, 'Northern Mariana Islands', 'MNP', 'northern-mariana-islands', 172, 1],
            [173, 'Norway', 'NOR', 'norway', 173, 1],
            [174, 'Oman', 'OMN', 'oman', 174, 1],
            [175, 'Other', 'OT', 'other', 175, 0],
            [176, 'Pacific Islands Trust Territory', 'PCI', 'pacific-islands-trust-territory', 176, 1],
            [177, 'Pakistan', 'PAK', 'pakistan', 177, 1],
            [178, 'Palau', 'PLW', 'palau', 178, 1],
            [179, 'Palestinian Territories', 'PSE', 'palestinian-territories', 179, 1],
            [180, 'Panama', 'PAN', 'panama', 180, 1],
            [181, 'Panama Canal Zone', 'PCZ', 'panama-canal-zone', 181, 1],
            [182, 'Papua New Guinea', 'PNG', 'papua-new-guinea', 182, 1],
            [183, 'Paraguay', 'PRY', 'paraguay', 183, 1],
            [184, 'Peru', 'PER', 'peru', 184, 1],
            [185, 'Philippines', 'PHL', 'philippines', 185, 1],
            [186, 'Pitcairn Islands', 'PCN', 'pitcairn-islands', 186, 1],
            [187, 'Poland', 'POL', 'poland', 187, 1],
            [188, 'Portugal', 'PRT', 'portugal', 188, 1],
            [189, 'Puerto Rico', 'PRI', 'puerto-rico', 189, 1],
            [190, 'Qatar', 'QAT', 'qatar', 190, 1],
            [191, 'Romania', 'ROU', 'romania', 191, 1],
            [192, 'Russia', 'RUS', 'russia', 192, 1],
            [193, 'Rwanda', 'RWA', 'rwanda', 193, 1],
            [194, 'Réunion', 'REU', 'reunion', 194, 1],
            [195, 'Saint Barthélemy', 'BLM', 'saint-barthelemy', 195, 1],
            [196, 'Saint Helena', 'SHN', 'saint-helena', 196, 1],
            [197, 'Saint Kitts and Nevis', 'KNA', 'saint-kitts-and-nevis', 197, 1],
            [198, 'Saint Lucia', 'LCA', 'saint-lucia', 198, 1],
            [199, 'Saint Martin', 'MAF', 'saint-martin', 199, 1],
            [200, 'Saint Pierre and Miquelon', 'SPM', 'saint-pierre-and-miquelon', 200, 1],
            [201, 'Saint Vincent and the Grenadines', 'VCT', 'saint-vincent-and-the-grenadines', 201, 1],
            [202, 'Samoa', 'WSM', 'samoa', 202, 1],
            [203, 'San Marino', 'SMR', 'san-marino', 203, 1],
            [204, 'Saudi Arabia', 'SAU', 'saudi-arabia', 204, 1],
            [205, 'Senegal', 'SEN', 'senegal', 205, 1],
            [206, 'Serbia', 'SRB', 'serbia', 206, 1],
            [207, 'Serbia and Montenegro', 'SCG', 'serbia-and-montenegro', 207, 1],
            [208, 'Seychelles', 'SYC', 'seychelles', 208, 1],
            [209, 'Sierra Leone', 'SLE', 'sierra-leone', 209, 1],
            [210, 'Singapore', 'SGP', 'singapore', 210, 1],
            [211, 'Slovakia', 'SVK', 'slovakia', 211, 1],
            [212, 'Slovenia', 'SVN', 'slovenia', 212, 1],
            [213, 'Solomon Islands', 'SLB', 'solomon-islands', 213, 1],
            [214, 'Somalia', 'SOM', 'somalia', 214, 1],
            [215, 'South Africa', 'ZAF', 'south-africa', 215, 1],
            [216, 'South Georgia and the South Sandwich Islands', 'SGS', 'south-georgia-and-the-south-sandwich-islands', 216, 1],
            [217, 'South Korea', 'KOR', 'south-korea', 217, 1],
            [218, 'Spain', 'ESP', 'spain', 218, 1],
            [219, 'Sri Lanka', 'LKA', 'sri-lanka', 219, 1],
            [220, 'Sudan', 'SDN', 'sudan', 220, 1],
            [221, 'Suriname', 'SUR', 'suriname', 221, 1],
            [222, 'Svalbard and Jan Mayen', 'SJM', 'svalbard-and-jan-mayen', 222, 1],
            [223, 'Swaziland', 'SWZ', 'swaziland', 223, 1],
            [224, 'Sweden', 'SWE', 'sweden', 224, 1],
            [225, 'Switzerland', 'CHE', 'switzerland', 225, 1],
            [226, 'Syria', 'SYR', 'syria', 226, 1],
            [227, 'São Tomé and Príncipe', 'STP', 'sao-tome-and-principe', 227, 1],
            [228, 'Taiwan', 'TWN', 'taiwan', 228, 1],
            [229, 'Tajikistan', 'TJK', 'tajikistan', 229, 1],
            [230, 'Tanzania', 'TZA', 'tanzania', 230, 1],
            [231, 'Thailand', 'THA', 'thailand', 231, 1],
            [232, 'Timor-Leste', 'TLS', 'timor-leste', 232, 1],
            [233, 'Togo', 'TGO', 'togo', 233, 1],
            [234, 'Tokelau', 'TKL', 'tokelau', 234, 1],
            [235, 'Tonga', 'TON', 'tonga', 235, 1],
            [236, 'Trinidad and Tobago', 'TTO', 'trinidad-and-tobago', 236, 1],
            [237, 'Tunisia', 'TUN', 'tunisia', 237, 1],
            [238, 'Turkey', 'TUR', 'turkey', 238, 1],
            [239, 'Turkmenistan', 'TKM', 'turkmenistan', 239, 1],
            [240, 'Turks and Caicos Islands', 'TCA', 'turks-and-caicos-islands', 240, 1],
            [241, 'Tuvalu', 'TUV', 'tuvalu', 241, 1],
            [242, 'U.S. Minor Outlying Islands', 'UMI', 'us-minor-outlying-islands', 242, 1],
            [243, 'U.S. Miscellaneous Pacific Islands', 'PUS', 'us-miscellaneous-pacific-islands', 243, 1],
            [244, 'U.S. Virgin Islands', 'VIR', 'us-virgin-islands', 244, 1],
            [245, 'Uganda', 'UGA', 'uganda', 245, 1],
            [246, 'Ukraine', 'UKR', 'ukraine', 246, 1],
            [247, 'Union of Soviet Socialist Republics', '???', 'union-of-soviet-socialist-republics', 247, 1],
            [248, 'United Arab Emirates', 'ARE', 'united-arab-emirates', 248, 1],
            [249, 'United Kingdom', 'GBR', 'united-kingdom', 249, 1],
            [250, 'United States', 'USA', 'united-states', 250, 1],
            [251, 'Uruguay', 'URY', 'uruguay', 251, 1],
            [252, 'Uzbekistan', 'UZB', 'uzbekistan', 252, 1],
            [253, 'Vanuatu', 'VUT', 'vanuatu', 253, 1],
            [254, 'Vatican City', 'VAT', 'vatican-city', 254, 1],
            [255, 'Venezuela', 'VEN', 'venezuela', 255, 1],
            [256, 'Vietnam', 'VNM', 'vietnam', 256, 1],
            [257, 'Wake Island', 'WAK', 'wake-island', 257, 1],
            [258, 'Wallis and Futuna', 'WLF', 'wallis-and-futuna', 258, 1],
            [259, 'Western Sahara', 'ESH', 'western-sahara', 259, 1],
            [260, 'Yemen', 'YEM', 'yemen', 260, 1],
            [261, 'Zambia', 'ZMB', 'zambia', 261, 1],
            [262, 'Zimbabwe', 'ZWE', 'zimbabwe', 262, 1],
            [263, 'Åland Islands', 'ALA', 'aland-islands', 263, 1],
        ];

        $now = Carbon::now();
        $records = array_map(fn ($c) => [
            'id'         => $c[0],
            'name'       => $c[1],
            'code'       => $c[2],
            'slug'       => $c[3],
            'sort_order' => $c[4],
            'is_active'  => $c[5],
            'created_at' => $now,
            'updated_at' => $now,
        ], $data);

        foreach (array_chunk($records, 100) as $chunk) {
            DB::table('countries')->upsert($chunk, ['id'], ['name', 'code', 'slug', 'sort_order', 'is_active', 'updated_at']);
        }
    }
}
